### ISSUE TITLE
[Bug/Information Missing?] Flint Hatchet doesn't count as axe.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [oitsjustjose/Natural-Progression#1]
**Information**
Flint Hatchet can't break wood as intended. There is no way to break wooden blocks in a modpack, because Flint Hatchet is only one tool, which can be crafted in inventory. It doesn't counts as axe?

**Expected behaviour**
There is a tooltip about how to use hatchet properly or Flint Hatchet breaks wooden blocks.

**Version**:
Forge: 28.1.69
Natural Progression: 1.0.1

**Comment by oitsjustjose** [comment]
Yup, literally just fixed it! 

https://www.curseforge.com/minecraft/mc-mods/natural-progressions/files/2818021

**Comment by DenisMasterHerobrine** [comment]
Thank you! Gonna try it now. :)
