### ISSUE TITLE
Idea: Draw Knife / Flint Scrapper and Solution for Tool Repair.

### ISSUE THREAD

**Issue by frakier** [oitsjustjose/Natural-Progression#10]
Flint Scrapper/Draw Knife/Bark Scrapper 
Flint Scrapper early game for stripping wood/working hides for leather. [flint] When you right click wood with a piece of flint it takes damage and becomes a tool instead of just a item.
Later in the game, use the draw knife/bark scrapper [metal and up] 

Solution for Tool Repair.
I'm using pickle tweaks it makes items repairable works good with this mod. It takes the same main ingredient to repair and you can set how many it takes to do the repair. So the tool breaks [flint axe], and you put the flint axe and three flints pieces in the 2x2 or 3x3 crafting and you repair the tool. Only draw back I have seen is when crafting planks sometimes the tool breaks and disappears but in that case you make a new tool which takes the the same ingredient plus a stick or two. So no big deal, maybe this will help with the suggestions for tool repairing.

**Comment by oitsjustjose** [comment]
I'm closing this for now as I don't think I'll be going in this direction. Sorry, but thank you for the suggestion!
