### ISSUE TITLE
No Early Tools Can be Crafted : Game Broken

### ISSUE THREAD

**Issue by Oscujic** [oitsjustjose/Natural-Progression#12]
Because of the feature that no wooden or stone tools can be crafted, it is impossible to ever be able to mine anything! Is this intentional??

**Comment by oitsjustjose** [comment]
Yes? Look into Bone Tools from Natural Progression. Kill mobs to get bones, knap bones with flint to get bone shards, make a bone pick. The bone pick can mine Iron-level tools.
