### ISSUE TITLE
[1.15.2] Crafting Sounds

### ISSUE THREAD

**Issue by TheUntamed** [oitsjustjose/Natural-Progression#17]
Why did you remove the Crafting Sounds in the latest version of the mod?
Was there a specific reason not just to add a config for toggling it?

**Comment by oitsjustjose** [comment]
There already was a config for toggling it, but in the end it didn't fit the mod. There was no reason for the sound other than something I thought I'd want, but it doesn't make sense for it to be in this mod. Sorry to disappoint!
