### ISSUE TITLE
[1.15.2] Feature Request

### ISSUE THREAD

**Issue by TheUntamed** [oitsjustjose/Natural-Progression#18]
I don't know if you plan to add more content for this mod, but if you plan to do so:

I'm sure you know the mod Primal Tech in MC 1.12.2. It added some very cool Survival content but it seems like it will not be updated to later Minecraft Versions.

Right now I really miss some good early game survival content for MC 1.15.2

It would be cool if you could bring back some of the content of Primal Tech.
E.G. 
Clay Kiln
Stone Grill
Water Powered Saw
Wooden Basin
Fluid Bladder
etc.

**Comment by TheUntamed** [comment]
A config to toggle the drop of pebbles from stone blocks would also be nice.

**Comment by oitsjustjose** [comment]
I feel that some of these things are desired from Primal Tech, but unfortunately my mod has no plans to adopt Primal Tech's features and has no relations with the mod at all. Sorry!

As for a config for the drops from pebbles, that also won't be easily possible but you can very easily change this with a DataPack.
