### ISSUE TITLE
No planks, I saw the old closed issue, still not working.

### ISSUE THREAD

**Issue by frakier** [oitsjustjose/Natural-Progression#2]
forge-1.14.4-28.1.68
NaturalProgression-1.14.4-1.0.2.jar
Nothing else...

Put logs and a hatchet into the 2x2 crafting are and nothing.
Tried with saws as well. Do not see any recipes [not sure if I would].
also tried with a 3x3 crafting.

Hope this helps

**Comment by oitsjustjose** [comment]
I may not have documented this well - you're meant to use *stripped* logs, not normal logs.

I'll find a way to clarify this *in game*.

**Comment by oitsjustjose** [comment]
![2019-10-28_20 40 56](https://user-images.githubusercontent.com/3887324/67728364-5fa37e80-f9c3-11e9-8205-2129f07250de.png)
![2019-10-28_20 40 48](https://user-images.githubusercontent.com/3887324/67728366-5fa37e80-f9c3-11e9-98eb-540ae4af9aeb.png)

Does this clarify things enough? I think it should do the job, just looking for input :smile:

**Comment by frakier** [comment]
Thanks.. Confirmed. 
Just update step 6 on the curse forge page from log to stripped log.
What's bad is I made a stripped log by accident and I never thought to follow through with testing it in the crafting grid though.
