### ISSUE TITLE
[1.15] Unable to craft modded planks with saw

### ISSUE THREAD

**Issue by FynnWaelsing** [oitsjustjose/Natural-Progression#20]
I'm using Autumnity, which adds Maple trees, together with this mod, and I can neither craft Maple planks in the traditional way nor with the saw or hatchet from this mod. Haven't checked with other mods, but the vanilla trees work fine.

Love the mod!

**Comment by oitsjustjose** [comment]
Seems related to #23  - this should be fixed at the same time as that is so keep an eye on that issue as I'll close this one :)
