### ISSUE TITLE
[1.15.2] Stone tools do nothing

### ISSUE THREAD

**Issue by NicolaSpadari** [oitsjustjose/Natural-Progression#21]
Re-enabling the stone tools in the config file restores recipes in game, however while mining or chopping wood, stone tools can't even start breaking the block. Just like i'm mining bedrock.

**Comment by oitsjustjose** [comment]
I've tested this and I can't reproduce this issue -- setting `removeStoneToolRecipes` to `false` works as expected. What version are you using?
