### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Sleepwaplker** [oitsjustjose/Natural-Progression#25]
I have not yet mastered the Git Hub, so I created a question for feedback. I made a translation into Russian for your mod, if you can come in handy.
[ru_ru.zip](https://github.com/oitsjustjose/Natural-Progression/files/4685308/ru_ru.zip)

**Comment by oitsjustjose** [comment]
Thanks a ton! I've implemented these for you but normally I'd suggest a Pull Request (read up on that [here](https://www.youtube.com/watch?v=rgbCcBNZcdQ) if you're interested).

These are the commits that implement your translations :) 82a5df3adb1c4af5cc686d2cb511bbefca8f9dac and ab30b103a863e18f9ed53d4f56839859aa136419
