### ISSUE TITLE
[MC 1.15.2] Immersive Engineering buzzsaw incompatibility

### ISSUE THREAD

**Issue by winnetrie83** [oitsjustjose/Natural-Progression#26]
This mod is preventing the buzzsaw with diamond blade (Immersive Engineering), to cut stones.
The message " you cannot mine hard blocks without a pickaxe" appears

**Comment by oitsjustjose** [comment]
Fine point -- I've added a workaround for this that allows pack developers to set which tools to ignore via a tag.
