### ISSUE TITLE
You can't punch trees to get resources, but you can punch stone?!!

### ISSUE THREAD

**Issue by SepSol** [oitsjustjose/Natural-Progression#3]
Just confused! It doesn't make any sense.

**Comment by oitsjustjose** [comment]
What do you mean, just the ability to sit there and punch stone items indefinitely, or specifically in reference to pebbles? 

Not a bad point though.

**Comment by SepSol** [comment]
It's that you cannot punch trees (because it's not realistic), but you can punch stones! Even though it drops nothing.

**Comment by SepSol** [comment]
What I mean by this is that the behaviors should be the same. Either you can punch and break both but it drops nothing, or you can't destroy stone blocks (Stone/Andesite/Granite/Diorite) and you have to get the proper tools before you can do so.
