### ISSUE TITLE
[1.16] Farmer's Delight and Natural Progression block breaking bug

### ISSUE THREAD

**Issue by rowanthemodder** [oitsjustjose/Natural-Progression#30]
### Versions and mods in the test environment
Forge: 35.1.36
Farmer's Delight: 0.2.4b
Natural Progression: 1.3.0

### Bug description
I am unable to break harvest level 0 blocks while holding Farmer's Delight knives, which is needed to gather straw.
[Farmer's Delight getting started wiki](https://github.com/vectorwing/FarmersDelight/wiki/Getting-Started)

### How to repeat
Hold any Farmer's Delight knife in your hand and attempt to break a harvest level 0 block such as grass, wheat, leaves, and dirt.

**Comment by oitsjustjose** [comment]
I just tested with the latest version of both mods, I don't have any issues with breaking tall grass with a knife to get straw. Can you reproduce and possibly send a gif/video?

Thanks!

**Comment by rowanthemodder** [comment]
![githubIssue](https://user-images.githubusercontent.com/46363164/104278444-79f93900-545d-11eb-897b-7303f652d11c.gif)
Here's a gif of it. I did some further testing and it seems this affects *only* the flint knife from Farmer's Delight, all other knives from Farmer's Delight work fine.

**Comment by oitsjustjose** [comment]
That's strange, I'm not doing anything to change that,... I've been having _lots_ of issues with breaking not working, I imagine something in Forge changed that I didn't catch.

**Comment by HopsandBarley** [comment]
Just started playing with this, and it only seems to be the flint knife that has a problem.  The iron knife from Farmer's Delight works on grass and leaves, as does diamond knife

**Comment by oitsjustjose** [comment]
Turns out, the "flint" knife uses the **Stone** tool type and the `REMOVE_STONE_TOOLS` recipe causes this to not work. I would advise that this is actually on VectorWing's side because a flint item should behave like flint, not stone. This unexpected behavior is on their end.

Sorry about that!

**Comment by vectorwing** [comment]
I used the Stone material mostly because the stats were just about what I wanted for the Flint Knife; didn't know it could affect behaviors such as this one.

Fair point; maybe I should create a new material for it. Thanks for spotting that! 👍

**Comment by vectorwing** [comment]
Done! Should be up in the next version of FD. Sorry for the trouble!
