### ISSUE TITLE
Unable to exchange blocks with exchanging wands

### ISSUE THREAD

**Issue by G-Stav** [oitsjustjose/Natural-Progression#31]
Tried with Botania's Rod of Shifting Crust and Building Gadget's Exchaning Gadget, the right click to change multiple blocks works, but left clicking to only exchange one at a time does not.
Maybe add a whitelist for items to break blocks with out any tool tags?
Forge 35.1.37
Natural Progression 1.16.4 1.3.0

**Comment by oitsjustjose** [comment]
Probably related to #30, I'll be looking into this as soon as I can ;)

**Comment by oitsjustjose** [comment]
So it's not related to #30, but I've added a new Item Tag that can be used to prevent these checks for specific tools:

`natural-progression:override_axes` and `natural-progression:override_pickaxes`. Add these items to both of those tags and you should have no issue.
