### ISSUE TITLE
Custom recipe not removing all required items after crafting

### ISSUE THREAD

**Issue by justinfleming** [oitsjustjose/Natural-Progression#32]
Using this recipe after removing the default recipe for furnace.

craftingTable.addShaped("Furnace", <item:minecraft:furnace>, [
    [<item:minecraft:cobblestone> * 2, <item:minecraft:cobblestone> * 2, <item:minecraft:cobblestone> * 2],
    [<item:minecraft:cobblestone> * 2, <item:minecraft:stick> * 10, <item:minecraft:cobblestone> * 2],
    [<item:minecraft:cobblestone> * 4, <item:minecraft:cobblestone> * 4, <item:minecraft:cobblestone> * 4]]);

The furnace is only crafted after entering the correct amount of items but when it is removed from the result window, it only removes one of each item.

**Comment by justinfleming** [comment]
oh is this what "but your ingredients all have to have a stack size of 1!" means in the example file? You can only have ingredients with 1 input?

**Comment by oitsjustjose** [comment]
I'm honestly not 100% sure I understand the context, are you using some feature of Natural Progression to make this recipe? Because your syntax is for CraftTweaker, and I don't  have any examples documented anywhere that I recall.

**Comment by justinfleming** [comment]
Sorry... Complete idiot, pasted to the wrong place. Oh the shame
