### ISSUE TITLE
new vanilla logs/Biomesoplenty compatibility?

### ISSUE THREAD

**Issue by justinfleming** [oitsjustjose/Natural-Progression#33]
Can this be made compatible with biomesoplenty wood types? I just realised that the hatchet works with vanilla logs, excluding new ones (eg crimson stem), and not with mod logs.

Great mod btw.

**Comment by Reotte** [comment]
Got the same issue, I really like this mod's knapping mechanic over "No Tree Punching" but this Log to Plank issue really breaks the early game, might as well break late game with the machineries using same recipies.

**Comment by oitsjustjose** [comment]
Sorry all, I'll get to it when I can. Work's been chaotically busy and that takes priority unfortunately. Hopefully this weekend I'll have time to look into this - this sounds like a bizarre issue. I think ToolTypes are broken in Forge currently? I'm having lots of issues with them both here and with the flint knife from Farmer's Delight (even though I don't do anything with it).

**Comment by oitsjustjose** [comment]
I've been working on merging in @sargunv-mc-mods's changes from a PR I neglected to review/merge, which should handle BOP recipes unless they've changed the paths to anything or added new things -- I'll also be working on adding the same for BYG.

I've also added Crimson/Warped Stem recipes as well!
