### ISSUE TITLE
Adding tools to axe tag makes them dupe when repairing

### ISSUE THREAD

**Issue by G-Stav** [oitsjustjose/Natural-Progression#34]
Added among other things easy steels flint hatchet to the axes tag, and when crafting two with low durability together and shift clicking it filled my inventory with hatchets, noticed on the last two that they had negative durability.

I'm guessing this had to do with the axe tag but will do more testing later today.

**Comment by G-Stav** [comment]
Nvm, guessing this one is on easy steels side, only happens with the flint hatchet. I'm guessing it has something to do with their giveback for their wool+hatchet = string recipe and two givebacks causing a dupe.

**Comment by oitsjustjose** [comment]
Oh ok, that makes sense. Thanks for figuring that out!
