### ISSUE TITLE
Config to turn off pebbles from stone?

### ISSUE THREAD

**Issue by HopsandBarley** [oitsjustjose/Natural-Progression#35]
This is more of a question than an issue.  Is there a way via config/datapack, etc to turn off pebbles dropping from stone when mined?  I didn't see anything in the config, but wasn't sure if there was a way to do it.

Thanks.

**Comment by oitsjustjose** [comment]
A data pack can do this, or you can put the Minecraft built-in data pack above the NP one like so:![image](https://user-images.githubusercontent.com/3887324/113595197-4bbf6b80-95fe-11eb-8250-690a95b08f8d.gif)
