### ISSUE TITLE
IE Rockcutter Blade for Buzzsaw won't mine Stone/Ore Blocks

### ISSUE THREAD

**Issue by czbuendel** [oitsjustjose/Natural-Progression#36]
Using version 1.4.0 in Engineer's Life 2 modpack we aren't able to use the IE Buzzsaw with a Rockcutter blade to mine stone or ore blocks. I am thinking that it stems from the Buzzsaw being classified as a axe normally, but with the rockcutter blade it can mine stone/ore as well with a silk touch effect.

**Comment by oitsjustjose** [comment]
If you searched "buzzsaw" you'd see that this has been reported and fixed via the 1.4.0 release. The pack developer needs to add the buzzsaw to the item tag `natural-progression:override_pickaxes`, and that should be it 🙂

**Comment by czbuendel** [comment]
My apologies! I will add that item tag to it. 😅
