### ISSUE TITLE
Request block tag check to address mod compatibility

### ISSUE THREAD

**Issue by D0CTOR-ZED** [oitsjustjose/Natural-Progression#37]
I'd like to request checking for a block tag on the target block to override the inability to mine hard materials without a pick similar to how you have a tag for tools.  Link for reference:

https://github.com/oitsjustjose/Natural-Progression/blob/f58870e8496313b2ef814e4a286e6364d5772485/src/main/java/com/oitsjustjose/naturalprogression/common/event/StoneBreak.java#L45

The issue we are having is the Charm woodcutter extends the stonecutter, but requires an axe.... but it's still stone material it seems.  Ideally, that should be fixed, but it probably isn't the only example where an override would help pack makers.  As it is, waila says to use an axe, but NP prevents the axe from chopping the stone block.  However, a pick will mine it fine.  If the harvest tool is an axe, an axe should work.  I guess that might be a second thing to add, if the tool matches the harvest type, let it work.  Thank you.

**Comment by oitsjustjose** [comment]
Sorry for the delay - lots going on! I've added this in commit 79c5a18550bcdf4551c4e36cb1001e6bc9e8b0fc

You can use the tag `natural-progression:ignored_stone_blocks` to add blocks (presumably stone but it doesn't matter) for which the pickaxe-requirement event checks, and the same for wood/axe with `natural-progression:ignored_wood_blocks`
