### ISSUE TITLE
Wrong position generation of grass and stone

### ISSUE THREAD

**Issue by Lamia5566** [oitsjustjose/Natural-Progression#38]
I found that some wrong generation of grass and stone.(They float on air)
I tested on 36.1.0 Forge and only using Natural-Progression.
I would like to ask is that vanilla bug or compatibility issue? Thank you.
https://imgur.com/NLX198K

**Comment by oitsjustjose** [comment]
Unfortunately this is a Vanilla bug that I can't fix. Sorry -- it drives me nuts too.

**Comment by Lamia5566** [comment]
> Unfortunately this is a Vanilla bug that I can't fix. Sorry -- it drives me nuts too.

Thank you for your reply~ Just a kindly remind.
According to MC-610 & MC-125858, it seems existed very long time ago, a old old Vanilla bug :3  . And this happens because terrain features are applied after trees and grass, causing them to appear in incorrect places. Only can fixing this would be fairly trivial, by making such features that change the terrain be applied before features that simply add things. 
It drives all of us nuts XDDD
