### ISSUE TITLE
Pebbles generating above Nether ceiling

### ISSUE THREAD

**Issue by Rascaliber** [oitsjustjose/Natural-Progression#39]
Found an issue where upon enabling the nether to spawn pebbles it spawns all of the rocks and sticks on the nether roof. I found this problematic if one were to use a mod that allows someone to spawn in different dimensions. If an individual were to spawn in the nether they would have no way to collect wood from the fungal forests.

**Comment by oitsjustjose** [comment]
This is fixed in 4f746144318da95e2bf206d23bd8e7b42d86930a 😊
