### ISSUE TITLE
Suggestion: 3D and more realistic pebbles

### ISSUE THREAD

**Issue by SepSol** [oitsjustjose/Natural-Progression#4]
![image](https://user-images.githubusercontent.com/47871887/68024663-0176e400-fcc0-11e9-93cb-c74aad8be33e.png)

This is from [A Crude Start ](https://www.curseforge.com/minecraft/mc-mods/a-crude-start)mod.

**Comment by SepSol** [comment]
It looks too big and low resolution with other textures. Something less noisy, less round-shaped (more right-angled) and 3D might go better both with vanilla and custom textures:

![image](https://user-images.githubusercontent.com/47871887/68024866-937eec80-fcc0-11e9-9087-168e64a0c49b.png)

**Comment by oitsjustjose** [comment]
Fair, those are just awfully chunky looking pebbles.

What do you think about these?

![image](https://user-images.githubusercontent.com/3887324/68035900-007f8b80-fc9b-11e9-829e-4b86823add33.png)

**Comment by SepSol** [comment]
This is much better!

**Comment by oitsjustjose** [comment]
Agreed, and it will work dynamically with any texture pack.

Thanks for the input!

**Comment by SepSol** [comment]
Thank you so much! They look much better now!
