### ISSUE TITLE
[1.16] Need help adding data pack compat for other modded woods

### ISSUE THREAD

**Issue by onemorelevel0** [oitsjustjose/Natural-Progression#40]
Hello, just wanted to say I really like your mod first (:. Anyway, I’ve been trying to add compat for several modded woods just thru datapacks, one of which being Bayou Blues. I’m able to add the new recipes for using the saw/axe tags and stuff, but it doesn’t get rid of the old log—>plank recipes. I saw the code you demonstrated in a previous issue for removing these log recipes, but I haven’t been able to find it within the mod (I assumed it would be under the RecipeRemover class files?). Are the .json files in the natural-progression folder the ones that are meant to override the normal log recipes? So I’m just curious how I can add compat for this mod and some others, including Abundance, Mysticsbiomes, & Better Default Biomes (probably some others too).

Also, the new netherite saw doesn’t have the saw tag on it, and the Upgrade Aquatic driftwood tags are only “upgrade_aquatic:driftwood” instead of “…driftwood_wood”, so a quick change in the data packs fixed it. The endergetic tags in the game are also normal (example: stripped_poise_wood instead of poise_wood_stripped or another variation), so the tags in the recipe files need to be fixed. For some reason the .json files for endergetic are formatted weird lol. And there’s a duplicate stripped log—>plank recipe under the saw files for endergetic. Anyways, any help or advice would be appreciated!

**Comment by oitsjustjose** [comment]
So you can do this a bit more easily using the Python scripts found here: https://github.com/oitsjustjose/Natural-Progression/tree/1.16/scripts/sawing_recipes

You can see my BOP example is still in `generate.py`. If you need further help let me know and I'll see what I can do!

**Comment by oitsjustjose** [comment]
Oh, two things I forgot:

1. the netherite saw tag has been added! thanks for point this out.
2. datapacks can be added on world creation by going to the DataPacks button in "More World Options", and just dragging your datapack folder or `.zip` in. Just in case you weren't aware! You may need to reprioritize your datapack above others like the mod whose planks you're trying to change the recipe for. See this little GIF for help: 

![https://cdn.discordapp.com/attachments/587777841760960544/820735969757888523/CleanShot_2021-03-14_at_14.06.47.gif](https://cdn.discordapp.com/attachments/587777841760960544/820735969757888523/CleanShot_2021-03-14_at_14.06.47.gif)
