### ISSUE TITLE
vanilla wood/stone tools config restricting wood and stone tools recipes

### ISSUE THREAD

**Issue by SabinaArmalite** [oitsjustjose/Natural-Progression#43]
if i try enabling wood and stone tools i can't remove the vanilla recipes to add new recipes, but if i disable them i can't craft stone or wooden tools at all

**Comment by oitsjustjose** [comment]
Looking into this now!

**Comment by oitsjustjose** [comment]
I cannot repro this, but for convenience I've stopped using somewhat hacky and unpredictable code. Instead I'm removing **only** wooden tool recipes using a datapack. You can learn more about datapacks [here](https://minecraft.fandom.com/wiki/Data_Pack).
