### ISSUE TITLE
terraforged, ice and snow biomes

### ISSUE THREAD

**Issue by SabinaArmalite** [oitsjustjose/Natural-Progression#44]
FIRST PROBLEM:
Terrain with ice still generates all kinds of rocks and twigs, i think twigs should be disabled from generating on certain blocks, an option to disable certain biomes/blocks from generating twigs and rocks would be nice, alternatively ice pebbles would be nice althought idk if you can get flint from ice.
it's mostly noticeable while playing with terraforged since large biomes can have large ice terrain generation zones where the ocean would be

The last issue might be something related with shaders but i'm not sure
SOME twigs and rocks that spawn in snow biomes seem to turn grass gray
could be a problem with biomes o plenty too but no idea since when you break the pebbles or sticks or right lick on them to pick them up the texture gets fixed

**Comment by oitsjustjose** [comment]
The twigs and pebbles above stone is an issue fixed in the 2.2 release. I'll go add a blacklist option for the next update :)

**Comment by oitsjustjose** [comment]
I have created two new config options: `twigPlacementBlacklist` and `pebblePlacementBlacklist` which defaults to `minecraft:ice, minecraft:packed_ice, minecraft:bedrock`. You can modify this to meet the needs of your pack 😀
