### ISSUE TITLE
stone and wood swords and tools appear to not be functional

### ISSUE THREAD

**Issue by JosephGallagher2001** [oitsjustjose/Natural-Progression#45]
So I crafted both stone and wood tools (swords specifically) but whenever I swing them, they do no damage. They don't even hit what I'm aiming at... Is there something about their functionality that I'm missing? If someone could help me with this, that'd be appreciated.

**Comment by oitsjustjose** [comment]
I have reworked this mechanic to be a bit more verbose- tool recipes are now removed via your own datapack, and tools being made useless have a more clearly written config option as well as a tooltip.
