### ISSUE TITLE
Suggestion: Add every entity drop bones option

### ISSUE THREAD

**Issue by Benjas333** [oitsjustjose/Natural-Progression#46]
Hey! I really love this mod and I was checking the config files to see what I was able to do. Then, I found the boneDropEntities option and I had an idea. I wanted to add every single entity to drop bones. But, I have like 60 mods and almost half adds new entities, so add every entity would be a pain. So, I think it would be good to add an option that makes every entity drop bones.

**Comment by oitsjustjose** [comment]
I can make this a config option.

**Comment by oitsjustjose** [comment]
Closing - this feature was added in b4b4753 - sorry for the delay!

**Comment by Benjas333** [comment]
Omg, thank you so much!
