### ISSUE TITLE
[Feature request] Whitelist to specify which blocks/tags are treated as wood/stone for breaking purposes

### ISSUE THREAD

**Issue by enduum** [oitsjustjose/Natural-Progression#47]
Example where this would be useful: Furniture mods tend to add mass quantities of wooden chairs/tables/etc and needing an axe for those seems silly, but manually adding _everything_ to `natural-progressions:ignored_wood_blocks` is... a bit of a task. Especially with a large amount of mods. In this scenario it would be much easier to just whitelist, eg, `minecraft:logs`.

Apologies if there's already an easy way to do this that I just haven't figured out. 😅

**Comment by oitsjustjose** [comment]
So, the way this works is that you'll need to create a new datapack - [this tutorial](https://minecraft.fandom.com/wiki/Data_Pack) is very helpful. Once you have it made, you'll need to create a file in `data/natural-progression/tags/blocks/ignored_wood_blocks`. Then fill it with something of the sort:

```json
{
  "replace": false,
  "optional": [
    "optional_modid:optional_block"
  ],
  "values": [
    "minecraft:oak_sign",
    "#minecraft:signs"
  ]
}
```

Yes, that's right - a tag can consist of a whole other set of tags! This may be useful on your quest :)

**Comment by enduum** [comment]
Thank you, I've got everything working the way I wanted now. 😄 I had tried to add tags to the tag before but I had the format wrong, lol.
