### ISSUE TITLE
Pebbles sometimes not waterlogging properly

### ISSUE THREAD

**Issue by PDallora** [oitsjustjose/Natural-Progression#49]
Some of the pebbles at the bottom of rivers and oceans are not waterlogged and create a pocket of water around them, while other pebbles are working fine. 
At times i also find them spawning at the bottom of tall grass blocks.

**Comment by oitsjustjose** [comment]
>  At times i also find them spawning at the bottom of tall grass blocks.

I have no idea how. I literally clear the block above the place I place the sample: https://github.com/oitsjustjose/Natural-Progression/blob/4bab467879c9670c6491e76c158ab54c0d35d35e/src/main/java/com/oitsjustjose/naturalprogression/common/world/feature/PebbleFeature.java#L54-L58

**Comment by oitsjustjose** [comment]
I've reworked some code for the next update that should hopefully solve this. If not, the only other thing I can do at this point is make pebbles "Tick" (like redstone ore or crops), which just seems a bit overkill.
