### ISSUE TITLE
Suggestion: what if you could also throw pebbles as an early weapon?!

### ISSUE THREAD

**Issue by SepSol** [oitsjustjose/Natural-Progression#5]

**Comment by oitsjustjose** [comment]
I've seen many other mods do this and my goal *isn't* to copy other mods, so I think I'll pass. Good suggestion though!!

**Comment by SepSol** [comment]
I'm new to using mods with Minecraft, so I haven't seen any of those ever, especially on 1.14.4 (Forge). But they could make the mid/late-game more fun and interesting since you'll have a use for what's on the ground - just saying! Your call eitherway.

**Comment by oitsjustjose** [comment]
> especially on 1.14.4 (Forge)

Yep! But I know for a fact one of the _many_ 1.12 mods for realistic beginnings offered this. I may reconsider, but for now, I think I won't be implementing this.
