### ISSUE TITLE
[Suggestion] Significantly More In-Depth Config

### ISSUE THREAD

**Issue by ThanEEpic** [oitsjustjose/Natural-Progression#52]
Hello! I'm not sure if this is the place to suggest ideas but I have one in mind that may lead to significantly more downloads of your mod. While your mod is extremely well done and has the absolute best 'no block punch' systems available, might I suggest that it include a more in-depth config system? Being able to enable or disabled certain recipes and especially whether or not pebbles drop from blocks(stone, andesite, etc.) could lead to a more customizable mod experience thus leading to more downloads of your mod. While CraftTweaker is often used to change such features, the ability to disable the pebble drop function would greatly increase ease in which newer modpack developers implement your mod into their packs, preventing them from getting frustrated and dropping the mod completely(which I see time and time again looking on Reddit and Discord threads discussing your mod). I appreciate your time and I look forward to hearing what you think!

Edit: While I understand that most of what modpack developers want to change can be done with datapacks, a lot of newer developers still do not possess the knowledge required for such a task. As I mentioned above, increased configurability of your mod will prevent the n00bs of the modpack world from dropping your mod completely.

**Comment by oitsjustjose** [comment]
I like this but I really don't have a lot of time nowadays to implement such a major change.
