### ISSUE TITLE
Modded axes are not compatible with "realistic" log crafting mechanics

### ISSUE THREAD

**Issue by viiizee** [oitsjustjose/Natural-Progression#55]
I noticed you removed the config option to disable the "realistic" log crafting mechanics. I do like the mechanic; however, it's not compatible with modded axes and therefor is extremely awkward when using this mod in a modpack..

**Comment by viiizee** [comment]
Also, the tools from Mowzies Mobs as well as other mods are not usable as they have the "The item is too blunt to use" tooltip.

**Comment by oitsjustjose** [comment]
You can fix this using the `override_axes` and `override_pickaxes` tags
