### ISSUE TITLE
[Suggestions] More uses for Bone, Harder Pickaxe

### ISSUE THREAD

**Issue by Squallll94** [oitsjustjose/Natural-Progression#59]
Since Bones drop now from more animals, there could be more uses for them:

Bone Armor
Bone Hatchet
Bone Arrow
Bone Spear

Also I think the Bone pickaxe is not quite realistic, instead there could be some primitive stone pickaxe, but much harder to obtain - for example with the use of many pebbles, maybe additional leather
Or to be more immersive and having another unique mechanic, maybe you need to place a cobblestone or even granite cobblestone onto the ground and then smash it with flint while the flint breaks to carve it into a pickaxe head with a hole for the handle.
This would in total cost like 15 flint or even more.

I think the flint tools could have a bit more durability, maybe in exchange be a bit less effective.

And finally it would be cool to have a flint ore - pretty much similiar to coal but drops flint - it's realistic and provides a good way to obtain more flint in modpacks where the pickaxe is not the end of the stone age.

Thank you for reading  ;)

**Comment by oitsjustjose** [comment]
I think I'm pretty happy with where NatProg is right now -- all of these features could be implemented at the modpack-level using KubeJS or Craft/ContentTweaker, so I think I'll have to pass on these great ideas. Thank you though!!!
