### ISSUE TITLE
[Compatibility] Storage drawers

### ISSUE THREAD

**Issue by CrusaderRabbit** [oitsjustjose/Natural-Progression#61]
Since storage drawers are made out of wood, whenever you try pulling things out of a drawer too fast, you end up taking damage for "punching wood." Is there a way to make this more compatible?

**Comment by oitsjustjose** [comment]
The Tag `natural-progression:ignored_wood_blocks` and `natural-progression:ignored_stone_blocks` can be used to do this :)

**Comment by oitsjustjose** [comment]
Replace `natural-progression` with `natprog` on 1.18 and up
