### ISSUE TITLE
[compatibility] Geolosys

### ISSUE THREAD

**Issue by CrusaderRabbit** [oitsjustjose/Natural-Progression#62]
Whenever I use a prospector pick on deepslate It says I can't break that block without a pickaxe

**Comment by oitsjustjose** [comment]
There Prospectors Pick isn’t a pickaxe, so this makes sense. Unless I misunderstand?

**Comment by CrusaderRabbit** [comment]
When you right click with the prospector's pick, the Natural Progression message prevents you from seeing the text from the propick results

**Comment by oitsjustjose** [comment]
I'm no longer maintaining Geolosys so I'm going to close this issue. Apologies for the inconvenience but I figure this two-year-old issue has probably been worked around in some way by now.
