### ISSUE TITLE
Cobbled blocks added by Natural Progression takes an extreme amount of time to break

### ISSUE THREAD

**Issue by CrusaderRabbit** [oitsjustjose/Natural-Progression#63]
Cobbled dripstone, andesite, diorite, granite, tuff, and netherrack, take almost 10 seconds to break with an iron pick while regular cobblestone takes 1.5 seconds to break.

**Comment by oitsjustjose** [comment]
Finally fixed in e3cd6749406554842886f8b57da30060abb2561c - thanks for the patience :)

**Comment by CrusaderRabbit** [comment]
Very nice thanks!
