### ISSUE TITLE
Natural Progression does not consider TConstruct's Mattock to be an axe

### ISSUE THREAD

**Issue by pouchrat** [oitsjustjose/Natural-Progression#65]
MC Version: 1.16.5
Forge Version: 36.2.9
NP Version: 1.16.5-2.3.2
TC Version: 1.16.5-3.3.4.335

I know it's because the mattock is coded as a shovel, but it's intended to be a multi-use tool. It'd be cool to be able to make exceptions for what can and can't be used on wood/hard blocks.

**Comment by oitsjustjose** [comment]
You can via Tags!! Just add your tool to the follow tags:

### For pickaxes:
`natural-progression:override_pickaxes`

### For Axes
`natural-progression:override_axes`

**Comment by F3R07** [comment]
> You can via Tags!! Just add your tool to the follow tags:
> 
> ### For pickaxes:
> `natural-progression:override_pickaxes`
> 
> ### For Axes
> `natural-progression:override_axes`

I have the same issue, but with the mod Super Tools, what do you mean add the tool to the following tags?
