### ISSUE TITLE
[compatibility] tetra

### ISSUE THREAD

**Issue by Nhaaro** [oitsjustjose/Natural-Progression#67]
Tetra's modular tools, specifically modular axes cannot be used as regular axes/saws in the stripped log/planks recipe

I tried adding them to the tags as a compatibility datapack, but seems like it's a lot more complex than I thought

The NBT tags that correspond to them look like this
```json
{
    "double/head_left": "double/basic_axe_left"
}
```

besides `axe`, there's also `adze` and `tomahawk` (this comes from an addon so it's not necessary), so the whole list might look like this
```json
{
    "double/head_left": "double/basic_axe_left",
    "double/head_right": "double/basic_axe_right",
    "double/head_left": "double/basic_adze_left",
    "double/head_right": "double/basic_adze_right",
    "double/head_left": "double/basic_tomahawk_left",
    "double/head_right": "double/basic_tomahawk_right",
}
```

Although it's not necessary for gameplay, I can always have a saw or two, it'd be a nice addition

**Comment by oitsjustjose** [comment]
Yeah currently supporting NBT-specific crafting isn't supported by Vanilla so doing so for my custom recipes won't be easy. I don't think this'll be doable as of now.
