### ISSUE TITLE
[Suggestions] Data-Driven Tags/Content

### ISSUE THREAD

**Issue by tacticalretard** [oitsjustjose/Natural-Progression#68]
Could we have tags for which blocks are hand-minable made accessible using datapacks, for customization in heavily modded games? Such customization would be beneficial for both mod compatibility and simple fine-tuning in modded worlds, and would undoubtedly improve accessibility for those who hand-craft specific modded experiences.

**Comment by oitsjustjose** [comment]
This is slightly more doable now with the new tags recently added, let me know if others are needed.
