### ISSUE TITLE
Not recognizing Super Tools

### ISSUE THREAD

**Issue by F3R07** [oitsjustjose/Natural-Progression#70]
When trying to use one of the tools with the Super Tools mod, for example the pickaxe, it says "You need the right tool for this job".
How do I add these tools to be recognized as legitimate tools with the natural progression mod?

**Comment by oitsjustjose** [comment]
Sorry for the impractically late reply - it's been a busy year+ and NatProg has been on life-support until now. You just need to add these tools to the tag `natprog:considered_as_axe` or `natprog:considered_as_pickaxe`
