### ISSUE TITLE
[Suggestion] Allow disabling knapping completely

### ISSUE THREAD

**Issue by LordPINE** [oitsjustjose/Natural-Progression#71]
The title says it all, I'd love a config that allows you to disable the knapping mechanic completely, as I'd like to use a custom replacement for it.

**Comment by SimonMeskens** [comment]
Seconded

**Comment by oitsjustjose** [comment]
Done via [4ec81b9](https://github.com/oitsjustjose/Natural-Progression/commit/4ec81b9a5df2ed912ceb314b76b30465c5803265) :) Backporting to 1.19 soon and releasing an update for both versions shortly!
