### ISSUE TITLE
[Compatibility] Origins

### ISSUE THREAD

**Issue by behaigo** [oitsjustjose/Natural-Progression#72]
One of the abilities you get from the Shulk origin is supposed to allow you to break stone without a tool.  It would be nice if being emptyhanded were treated as being the right tool for mining stone if this option is selected.

v1.19.2

**Comment by oitsjustjose** [comment]
Origins support really isn't planned and the API doesn't seem to be clear enough to just "get origin from player" like I'd expect, so I won't be able to do this one for now. If the Origins API updates to be a little more dev-friendly I'll be glad to re-visit. Sorry!
