### ISSUE TITLE
[Issue] Quark pickarang and its variants not classified as pickaxes

### ISSUE THREAD

**Issue by Dakotaraptor** [oitsjustjose/Natural-Progression#73]
They cannot break stone or any other pickaxe-breakable blocks with Natural Progression installed. Adding a config option to allow certain tools to bypass NP's progression system would be a good way of avoiding such issues in the future.

**Comment by oitsjustjose** [comment]
Should have been resolved in the latest release!

**Comment by rockrevenchy** [comment]
![image](https://github.com/user-attachments/assets/5b3371b7-a5d1-4f5f-968f-05258aa56387)
as of today, this issue seems to be still relevant and i'd like to reopen it

natural progression 2.3.8
quark 4.0-460
Minecraft 1.20.1
Neoforge 47.1.106
