### ISSUE TITLE
Plant fiber for use in fire starter craft

### ISSUE THREAD

**Issue by xeaal** [oitsjustjose/Natural-Progression#75]
Hello. Can you please add some kind of plant fiber that you can collect with a knife and then use interchangeably with a string (at least for early-game primitive tools like fire starter)? Or just maybe make it so you don't need a string to make a fire starter.

**Comment by oitsjustjose** [comment]
This is a bit out of the scope for my plans for NatProg - you can always do something like this as a pack developer using KubeJS though!
