### ISSUE TITLE
Create pebbles broken textures 1.19.2

### ISSUE THREAD

**Issue by SweetlilTrinket** [oitsjustjose/Natural-Progression#76]
Minecraft version: 1.19.2
Mod version: 2.3.5
Forge version: 43.2.21
Issue: pebbles for create stone types have broken textures  but still spawn in the world not sure why. 

![retghqwethq](https://github.com/oitsjustjose/Natural-Progression/assets/60005826/e2cd037d-9275-4ed0-a4bc-c2ad7b6bcd16)
![Capture](https://github.com/oitsjustjose/Natural-Progression/assets/60005826/473f1469-8eed-44fc-aa73-e1edf8159b8b)

**Comment by DanDragonWolf** [comment]
These are also broken in 1.20.1

**Comment by oitsjustjose** [comment]
Fixed via [d1f60e5](https://github.com/oitsjustjose/Natural-Progression/commit/d1f60e54d9f7eae21e74aa3055ced7dc582136bc) - update coming out soon for 1.20 and 1.19 :)

![image](https://github.com/oitsjustjose/Natural-Progression/assets/3887324/54f3df19-d306-4524-9c43-08fee688bb4a)

**Comment by doarlock** [comment]
This is happening on 1.18.2-2.3.4. I have installed create 1.18.2-0.5.1.h
