### ISSUE TITLE
Request: Nerf attack speed or damage of saws and flint axe

### ISSUE THREAD

**Issue by Silvertide7** [oitsjustjose/Natural-Progression#78]
Some mods / modpacks disable the vanilla 10 tick damage immunity after being damaged. The saws/axe this mod adds have higher dps than most end game weapons because of that. It would be cool if you could turn those down to normal axe values, or add a config for players who would like to change it.
Thanks for the great mod!

**Comment by oitsjustjose** [comment]
I think this would ultimately be up to the pack designer. Changing run-time attributes of tools is usually left up to KubeJS rather than the mod itself, so I'm probably going to pass on this request. Sorry!!
