### ISSUE TITLE
[Bug] Placing pebble deletes existing pebble or twig

### ISSUE THREAD

**Issue by Br00t4L17y** [oitsjustjose/Natural-Progression#79]
Minecraft 1.20.1
Forge 47.2.1

Example:
If you have a stone pebble in hand, and come across a twig or an andesite/dolorite etc pebble, and you right-click to place your pebble, it will delete the twig or the other type of pebble from the world, and place your stone pebble on top of it. Conversely works, if you locate a twig or stone pebble on the ground, and place a andesite/dolorite pebble on top of it.

**Comment by oitsjustjose** [comment]
This is unfortunately not something I can fix - the block is either not replaceable at all, or it's replaceable by anything 😭
