### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [oitsjustjose/Natural-Progression#8]
Actually, this isn't a issue, but maybe add compatibility with the wood/trees/tools(like axes) from another mods, it's kinda annoying sometimes that you can't craft Normal/custom wood with normal/custom axes because incompatibility :/, mods like:

-Forbidden N Arcanus
-Explorercraft
-The Midnight
-Druidcraft
-Etc etc.

And also, i love so much this mod, makes game harder even if you are further on the gameplay.

**Comment by oitsjustjose** [comment]
You can always create a data pack. I have done the same for my mod server
and everything’s working wonderfully.

**Comment by Mr-Blazkowicz** [comment]
Sadly, idk how how to make datapacks, even code :c

**Comment by oitsjustjose** [comment]
Take this as an example:

[Modpack Compat.zip](https://github.com/oitsjustjose/Natural-Progression/files/3902049/Modpack.Compat.zip)

When you want to test your datapack, compress (zip) the file and move the .zip file in your `saves/<your save>/datapacks` directory, then type `/reload` if the game is currently running. You can type `/reload` as many times as you need while developing your datapack.

The zip I included already has Druidcraft darkwood compat written in there as an example. For other resources I'd suggest [this video I made a few months ago](https://www.youtube.com/watch?v=-NF2B5Qr87o&t=2s) and [this wiki page](https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack) for anything I forgot.
