### ISSUE TITLE
[Request] Randomize pebble and twig models on ground

### ISSUE THREAD

**Issue by Br00t4L17y** [oitsjustjose/Natural-Progression#80]
Feature request:

Natural Progression twigs and pebbles are lacking in variety. It would be really great to see randomized models for each spawn of these resources, similar to the models found in the mods This Rocks! and Project: Vibrant Journeys.

**Comment by oitsjustjose** [comment]
I'm honestly not the best texture artist or modeler - this can easily be done with a resource pack and I'm open to accepting new art if offered, but I lack the skill and time to do this myself. Thanks for the suggestion though!!
