### ISSUE TITLE
Create Pebbles Appearing Without Textures.

### ISSUE THREAD

**Issue by Cheesedoghotdog** [oitsjustjose/Natural-Progression#81]
Hey, just tried adding Create to this mod and the various pebbles based on Create stones are showing up as missing textures. Is there any way to disable these pebbles? This is on the Forge 1.20.1 version of both mods.

**Comment by oitsjustjose** [comment]
Duplicate of https://github.com/oitsjustjose/Natural-Progression/issues/76 - working on this now.
