### ISSUE TITLE
[Feature Request] Disable damage option

### ISSUE THREAD

**Issue by Saereth** [oitsjustjose/Natural-Progression#82]
currently your code here
https://github.com/oitsjustjose/Natural-Progression/blob/d55788f2daedd7f54a72632487f974410ab26e50/src/main/java/com/oitsjustjose/natprog/common/event/block/WoodBreak.java#L36

triggers on things like storage drawers, or in the case of jade/jade ons which calc your breakspeak for the ui display, it triggers just by looking at wood blocks which leaves players wondering why they are seemingly randomly taking damage just walking around. It would be nice to be able to just turn this damage off in the config or at least let us tag blocks to be ignored.

**Comment by Saereth** [comment]
Made a pr for the feature if accepted, 
https://github.com/oitsjustjose/Natural-Progression/pull/83

**Comment by oitsjustjose** [comment]
Approved & Merged, thank you!!
