### ISSUE TITLE
Some items from other mods are "incorrectly" marked as too brittle or blunt to use.

### ISSUE THREAD

**Issue by Baelarius** [oitsjustjose/Natural-Progression#87]
Some items from other mods are "incorrectly" marked as too brittle or blunt to use. For example the Naga Fang Dagger & Spear from Mowzie's Mobs (mowziesmobs:naga_fang_dagger & mowziesmobs:spear). Is there a some way (a tag perhaps?) to override this mod's setting of these items as too brittle / too blunt to use?

**Comment by oitsjustjose** [comment]
You can add these to the tag `natprog:considered_as_axe` or `natprog:considered_as_pickaxe` to each tool :)

**Comment by Baelarius** [comment]
Nifty, thanks!

**Comment by Baelarius** [comment]
However, after adding the tag (natprog:considered_as_axe) to both items, they are still "labeled" as "Too blunt to use" and they are still un-usable. Do they also need to have the minecraft:tools &/or forge:tools tags as well?

**Comment by oitsjustjose** [comment]
Oh sorry I misunderstood the issue!!!

Allowed wooden tools should have the tag `natprog:allowed_wooden_tools` and allowed stone tools should use `natprog:allowed_stone_tools`. Sorry for the confusion!!

**Comment by Baelarius** [comment]
Ahh, that makes more sense as well, thanks again.

Love Natural Progression, btw, its a lovely mod.

**Comment by Baelarius** [comment]
Quick question, I noticed that two items which should be disallowed (specifically the wood & stone knives from More Delight) are fully operational, are their tags like the "allowed" ones to manually "disallow" specific items?
