### ISSUE TITLE
Suggestion: Please add a config to enable tree punching

### ISSUE THREAD

**Issue by pskfyi** [oitsjustjose/Natural-Progression#88]
I love that tree punching is disabled - it's core to the NatProg experience. But now I'm trying to use it in a SkyBlock pack, to make use of its pebbles, tools, and tool damaging recipes, and the inability to punch trees means I would have to warp the pack significantly if I wanted to include NatProg.

Last year on Discord, you seemed open to the idea of adding a config for this. ([message link](https://discord.com/channels/587748164841504795/848058442895458304/1137144708632686763)) Is that still a possibility?

**Comment by oitsjustjose** [comment]
Ah right, yeah this project has been on the side-burner. I've completed this via f8e608944c68973dbed1551c9af92e66c844dec9 -- I've got other fixes and stuff coming together for an update release later today :)
