### ISSUE TITLE
Issue in 2.3.7 with breaking #forge:stone and #minecraft:logs

### ISSUE THREAD

**Issue by MayD524** [oitsjustjose/Natural-Progression#89]
In my custom 1.20.1 mod pack and when using natural progression by itself. I was not able to break any block with the tag #forge:stone or #minecraft:logs with the proper tools.

This issue only exists on the latest 2.3.7 version of the mod, but not the 2.3.6 version and I've only seen this behavior in 1.20.1 so I'm not sure if it exists in other versions.

**Comment by oitsjustjose** [comment]
Was this with your bare hands or with a tool?

**Comment by oitsjustjose** [comment]
Boy I am not good at reading 😒 

On it, I think I see the issue :)

**Comment by oitsjustjose** [comment]
Resolved in 2.3.8 which is pending approval :)

**Comment by MayD524** [comment]
Thank you so much! :)
