### ISSUE TITLE
No information on how to knap pebbles

### ISSUE THREAD

**Issue by Syndaryl** [oitsjustjose/Natural-Progression#9]
The Curseforge is the only documentation I can find, and it just says "knap pebbles into flint". I've tried right-clicking into air with multiple pebbles (does nothing), left clicking into air (attacks), right clicking onto a stone block (places pebble), and left clicking onto a stone block (complains I can't dig bare handed).

How do?

**Comment by oitsjustjose** [comment]
The latest version of Natural Progressions has detailed tooltips that should help!

But it's simple: Hold a pebble in your main hand, and another in your off hand. Hold down right click -- if you're on an older version, make sure not to look at a block while doing this!

**Comment by Syndaryl** [comment]
Aha! Thanks :)
